# Configuration file to run tests on Travis-CI via GitHub notifications
language: python
python:
    - "2.7"

notifications:
    email: false

sudo: false

addons:
  apt:
    packages:
    - python-dev
    - python-numpy
    - python-scipy
    - python-tk
    - python-matplotlib
    - libfreetype6

before_install:
    - export PATH=/home/travis/miniconda/bin:$PATH

install:
    - pip install biopython pandas pysam pyvcf reportlab
    - python setup.py install
    # For codecov.io
    - pip install codecov

before_script: cd test/
script:
    - coverage run test_cnvlib.py

after_success:
    - coverage report
    - codecov
