# Configuration file to run tests on Travis-CI via GitHub notifications
language: python
python:
    - "2.7"

notifications:
    email: false

sudo: false

addons:
  apt:
    packages:
    - libblas-dev
    - libfreetype6-dev
    - liblapack-dev
    - python-dev
    - python-matplotlib
    - python-numpy
    - python-scipy
    - python-tk

before_install:
    - pip install biopython pandas pysam pyvcf reportlab
    # For codecov.io
    - pip install codecov

install:
    - python setup.py install

before_script: cd test/
script:
    - coverage run test_cnvlib.py

after_success:
    - coverage report
    - codecov
