# Configuration file to run tests on Travis-CI via GitHub notifications
language: python
python:
    - "2.7"

notifications:
    email: false

sudo: false

before_install:
    # Set up anaconda
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH

install:
    - conda update --yes conda
    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib biopython reportlab pysam pyvcf pandas
    - python setup.py install
    # For codecov.io
    - pip install codecov

before_script: cd test/
script:
    - coverage run test_cnvlib.py

after_success:
    - coverage report
    - codecov
