# Configuration file to run tests on Travis-CI via GitHub notifications
language: python
python:
    - "2.7"

notifications:
    email: false

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
    - "sudo apt-get update -qq"
    - "sudo apt-get install -y libopenblas-base liblapack3gf python-numpy"
install:
    - "pip install scipy matplotlib reportlab biopython pysam"
    - python setup.py install


# before_install:
#     # Setup anaconda
#     - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
#     - chmod +x miniconda.sh
#     - ./miniconda.sh -b
#     - export PATH=/home/travis/miniconda/bin:$PATH
#     - conda update --yes conda
#     # Avoid a crash with multiprocessing on Travis; not specific to Miniconda
#     - sudo rm -rf /dev/shm
#     - sudo ln -s /run/shm /dev/shm
# install:
#     - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib
#     - pip install reportlab biopython pysam
#     - python setup.py install


before_script: cd test/
script: python test_cnvlib.py

